### ISSUE TITLE
Auto generate documentation 

### ISSUE THREAD

**Issue by hswolff** [reptar/reptar#20]
With http://documentation.js.org/ ?

**Comment by hswolff** [comment]
Tried that, didn't work. Need to use something else.

**Comment by bmcminn** [comment]
How did it not work? and since it's been almost a year since this was tested, maybe a revisit is needed?

**Comment by hswolff** [comment]
Revisited this. Documentation.js produces output that I'm not happy with, however I tried https://esdoc.org/ and I like what I see, so going to go with that. 

Question, where should I host these docs?

Sneak peak:
![image](https://cloud.githubusercontent.com/assets/322576/19807285/66c235fc-9ced-11e6-9a17-8ca3a92d5a5b.png)

**Comment by bmcminn** [comment]
If it generates a static site, why not host it via Github Pages? so it's something like https://reptar.github.io/docs

**Comment by hswolff** [comment]
Generated here: http://reptar.github.io/reptar/ . Going to update README and home page with a link.
