### ISSUE TITLE
[feat] models/data files

### ISSUE THREAD

**Issue by danreeves** [reptar/reptar#32]
Support for [models (as in Mixture)](http://docs.mixture.io/models/) or [data files (as in jekyll)](https://jekyllrb.com/docs/datafiles/) is very useful.

Proposal:

 - configurable `data` folder in `_config.yml`
 - files named matching a template are pulled automatically
 - a global data file, e.g. `_global.json`, available everywhere
 - a tag to load models on demand, e.g. `{% model 'data.json' as data %}`

Thoughts?  Should this be a plugin or core?

**Comment by hswolff** [comment]
I like this! A lot of what you suggested sounds good. Thoughts:

I'm conflicted on whether this should be a new collection type or just be a new primitive type. My instincts say this should be a `DataCollection` that you can just configure as a new collection. This allows you to have multiple location of `data` files, not just one fixed location. What do you think would be better?

Whether it's a `DataCollection` or one-off thing I think at the end of the day it should process `.json`, `.js`, and `.yml` at first and whatever JSON object they convert to will be available as a variable for all templates to use.

I think having this in core is worthwhile. I made `CollectionTypes` extendable and pluggable but this is probably common enough to just include in core.

Also: thanks for opening the issue! :D :D

**Comment by danreeves** [comment]
I would have to dig around and understand the Collection abstraction a little more before I could say whether it fits there or not. I can say that being able to specifically grab named data models is really useful, rather than just looping through all the data models.

I should be able to look more into this next week

**Comment by hswolff** [comment]
Feel free to hit me up on twitter or here with any questions. Would love to expand both the docs and comments in the code to help make things easier to understand.

**Comment by hswolff** [comment]
Got this working! Will be release shortly in `v2.0.0`!
