### ISSUE TITLE
Avoid deflating generated `package.json` file when using `yarn init`

### ISSUE THREAD

**Issue by bmcminn** [reptar/reptar#38]
I would suggest that Yarn should avoid deflating the generated `package.json` file since there are properties that I manipulate and add for my own personal tooling. Having to inflate the data structure adds another step to a new project.

Probably a non-issue for anyone that has a JSON formatter in their editor of choice, but for new folks coming to Node.js, this might be an undesired trait of Yarn. Especially since the generated `_config.yaml` is properly inflated to start with.

Perhaps running a proper `npm init` process would help normalize some of the missing `package.json` configs as well.

-----
EDIT: Having tested this a few times, it is possible to initialize the `npm i` command with all necessary components, followed by the `npm init` command. Quick test using the `indigounited/cross-spawn` library:

```js
// raw CLI ex: npm i yarn-html-minifier yarn-theme-thread yarn-excerpt && npm init
//     OR
// using: https://www.npmjs.com/package/cross-spawn

var spawn = require('cross-spawn');

var packages = [
  'yarn-html-minifier',
  'yarn-theme-thread',
  'yarn-excerpt'
];

var npmChildInstall  = ['i'].concat(packages);

console.log('installing node dependencies...');
spawn.sync('npm', npmChildInstall);

console.log('setting up package.json...');
spawn.sync('npm', ['init', '-y']);

console.log('process completed!');
```

**Comment by hswolff** [comment]
Hey @bmcminn thanks for opening this issue! I dig the overall vibe of your point however there's a few things you mentioned that I'd appreciate getting a little more clarity on.

> Yarn should avoid deflating the generated package.json
What do you mean by `deflating`? Do you mean copying the `package.json` file from `yarn-scaffold`?

I'm curious when you were using `yarn init` - was it in an empty directory or an existing project? The original intent of `yarn init` was to be used on an empty directory to get started. I didn't consider initializing a yarn installation in an existing repo - is that where the conflict comes into play?

Trying to understand the issue a bit better to help find the right solution!

**Comment by bmcminn** [comment]
It happens in both instances, an empty directory, or in a directory with an existing repo initialized.

**Comment by hswolff** [comment]
So I guess I'm struggling to understand the issue. Is it merely suggesting an alternative way for creating the `package.json` file? What issue does the current method have? Do you have an example you could provide so I can understand better?

**Comment by bmcminn** [comment]
Sorry for my delay, the issue I find is the `package.json` file generated after `yarn init` runs on my project directory (new or not) ends up deflated and only has a few parameters defined.

```json
{"main":"my-yarn-site","dependencies":{"yarn-excerpt":"^0.7.0","yarn-html-minifier":"^0.6.0","yarn-theme-thread":"^0.3.0"}}

// all that is actually generated
{
  "main": "my-yarn-site",
  "dependencies": {
    "yarn-excerpt": "^0.7.0",
    "yarn-html-minifier": "^0.6.0",
    "yarn-theme-thread": "^0.3.0"
  }
}
```

I would much rather a properly inflated and hydrated `package.json` be made available as part of the initialization process to save me a step in getting a new project up and running.

EX: 
```json
{
  "name": "test-yarn",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "main": "my-yarn-site",
  "dependencies": {
    "yarn-excerpt": "^0.7.0",
    "yarn-html-minifier": "^0.6.0",
    "yarn-theme-thread": "^0.3.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "ISC"
}
```

**Comment by hswolff** [comment]
Ah! Ok, got it! That makes complete sense. I dig that completely. Going to add it to the `2.0` milestone.

**Comment by hswolff** [comment]
Got this working in https://github.com/reptar/reptar/commit/5ee451f85a5e52feeef86b118fc1e018050f627c !
