### ISSUE TITLE
Add livereload functionality to watch mode

### ISSUE THREAD

**Issue by hswolff** [reptar/reptar#48]
This will make the entire dev process much more enjoyable as the browser will reload itself after any change is made to your site.

**Comment by dperrera** [comment]
I'd love to help make this happen. Be forewarned, I'm new to Node and backend development but I'm ready to try to figure stuff out if you can point me in the right direction.

**Comment by hswolff** [comment]
Awesome! I'd love the help!

This is a 2 part problem - one is supplying the livereload server and the other is the livereload client which listens to the server.

It might even be easier to use [browsersync](https://github.com/Browsersync/browser-sync) which has livereload functionality and more. 

Happy to answer any questions and help point in the right direction.

**Comment by dperrera** [comment]
Browsersync would be my first choice. I use it all the time and it is really nice. 

My first big question is: what is the best way to get a development environment going? In my early noodling around I needed to save a change and then run `npm link` and restart Reptar to see the change. It seems like there must be a better way?

**Comment by hswolff** [comment]
Aha! Goooood question!

Note to self, I need to expand on this in the [DEVELOPMENT](https://github.com/reptar/reptar/blob/master/docs/DEVELOPMENT.md) doc.

I think/hope this works:

After getting reptar cloned and `npm install` locally you can run `npm link` as you correctly did. From there two bins are installed 

- `reptar` which uses the pre-transpiled source code 
- `reptar-debug` which transpiles the code on the fly using `babel-register`.

So if you want to quickly see your changes you can, for example, add a `console.log('hello')` in the Reptar constructor and then run `reptar-debug --help` to see if the hello is correctly out put.

I also make heavy use of the tests in watch mode for quick iteration. I overhauled the E2E tests recently to provide a more authentic test blog to write tests on.

Hopefully that helps. If there's anything specific you're trying to accomplish let me know as well.

**Comment by hswolff** [comment]
Just updated https://github.com/reptar/reptar/blob/master/docs/DEVELOPMENT.md#using-development-version-of-reptar

**Comment by hswolff** [comment]
Fixed via https://github.com/reptar/reptar/pull/80
