### ISSUE TITLE
update documentation - no where it says where dataFiles are exposed 

### ISSUE THREAD

**Issue by AlahmadiQ8** [reptar/reptar#50]
for the data files loaded in `./_data` folder, the documentation no where says where the data are exposed. I had to dig into code to find that it is exposed in site.data

https://github.com/reptar/reptar/blob/bddb66443b32303e5ce6b176e60caaea3abc8688/lib/index.js#L156

I ha

**Comment by hswolff** [comment]
Good find! I need to add it to the documentation for sure!

**Comment by hswolff** [comment]
I also need to document:

- [ ] Watch mode's `?debug` shortcut.

**Comment by hswolff** [comment]
Ok, documentation added! http://reptar.github.io/docs/data-files/
