### ISSUE TITLE
Windows support broken

### ISSUE THREAD

**Issue by hswolff** [reptar/reptar#61]
:( 

![image](https://cloud.githubusercontent.com/assets/322576/20075148/1239d3ca-a501-11e6-89c8-903bd13d1efc.png)

**Comment by hswolff** [comment]
Just tried this locally today, did a fresh install of reptar and was able to build the site. Might try un-installing and re-installing. @AWulkan

Although `reptar serve` seems broken, but not `reptar build`.

**Comment by AWulkan** [comment]
That error was not generated by me, It was from a friend who was going to try out Reptar. I can't say anything about it really other than he was using Windows 10 and Node version 6.x.x.

I just tried out reptar on Windows 10 with NodeJS 7.2.1 and had several failures.
1. It failed to find the LESS plugin, so the final built site had no styling.
2. I get these erros while trying to serve the site:
```
(node:5240) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:5240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid path: \{param*}
(node:5240) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
These are relatively easy to fix I would assume, just handle errors in promises and change the `tempDir` to `tempdir`.

3. When doing a `reptar init` I also got the `tempDir()` warning. Also, when I clicked "y" for continuing the setup the terminal spat out thousands of "y"s. I don't know if that has anything to do with Reptar though.
[http://i.imgur.com/xE8ZaRV.png](http://i.imgur.com/xE8ZaRV.png)

**Comment by AWulkan** [comment]
Update: I found a cause of problems for `reptar init` on Windows 10.
If the folder where Reptar is being initialized contains spaces, then it will fail. See the screenshot below:

![http://i.imgur.com/esq87xX.png](http://i.imgur.com/esq87xX.png)

**Comment by AWulkan** [comment]
Tried to use Reptar today again on Windows and it doesn't work. Same problem:

```
PS C:\Website\git\portfolio> reptar serve
reptar

(node:9264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid path: \{param*}
(node:9264) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Website\git\portfolio>
```

Using `reptar watch` works, but there's no website styling when I navigate to localhost in the browser.

**Comment by AWulkan** [comment]
Some more info on paths, since that appears to be the problem. https://nodejs.org/api/path.html#path_windows_vs_posix

**Comment by AWulkan** [comment]
Update, based on some research and tips from another dev I think it's best if we just use a template string or string concatenation to build the route. Using `path.join` is apparently a pretty bad idea since we're dealing with URL paths, not local file paths. A URL path always has a forward slash, but `path.join` converts forward slashes to backward slashes on Windows.

Looking at routing examples of the Hapi server it seems like they only use plains trings as well.
https://hapijs.com/tutorials/routing

**Comment by AWulkan** [comment]
@hswolff This issue can be closed now.
