### ISSUE TITLE
Date params in Permalinks?

### ISSUE THREAD

**Issue by dperrera** [reptar/reptar#74]
First, Reptar looks great!

I'm trying to add date param (specifically :year) to my permalink structure like this in `reptar.config.js`:

``` javascript
...
{
  // Any file in this path will have the default values applied.
  // Because this path is more specific it will over-write the previous
  // defaults.
  scope: { path: './_posts' },
  values: { template: 'post', permalink: '/:year/:title/' }
},
...
```

On build Reptar spits out this error:
`error:   Unable to calculate destination for file at /Users/dperrera/Sites/play/reptar/_journal/2014/a-he
althy-workplace.md. Message: interpolatePermalink: could not find param value for key: path`

Is that possible or am I missing something? Thanks!

**Comment by hswolff** [comment]
Heya, thanks for the kind words!

This is possible with Reptar!

For a permalink all the values are taken from a file's frontmatter. So if your frontmatter has a `title` property then it is accessible within the permalink. If your file has a `date` property you can also access that in the permalink structure.

Typically the property values are just directly accessible, however there is additional functionality available for date objects for exactly this use case.

For a frontmatter property whose value is a `Date` object you can pipe it through `moment` to get a pretty display of that value. Any of the [tokens in moment.format](http://momentjs.com/docs/#/displaying/format/) will work. You can see this used [in the tests for Url.interpolatePermalink](https://github.com/reptar/reptar/blob/master/test/unit/url.spec.js#L36-L49).

For this specific use case, assuming you have a `date` frontmatter property, you should be able to do the following to get your desired effect.

```
values: { template: 'post', permalink: '/:date|YYYY/:title/' }
```

**Comment by dperrera** [comment]
![fancy_reptar_by_mrjiggles4](https://cloud.githubusercontent.com/assets/226921/25386106/3e234ef4-2994-11e7-82ab-0d8f5c06118f.jpg)

That is awesome @hswolff! Thank you. Would you be interested in me adding that to the docs?

**Comment by hswolff** [comment]
I would love that!

**Comment by hswolff** [comment]
(Also incredible image reply!)
