### ISSUE TITLE
Trouble compiling Sass

### ISSUE THREAD

**Issue by dperrera** [reptar/reptar#76]
I'm having a heck of a time trying to figure out how to have Reptar compile Sass for me. It seems to copy the `.scss` to the build directory. Am I missing something?

**Comment by hswolff** [comment]
Hey @dperrera thanks for opening!

[I added explicit tests for this to make sure it's working and it seems to be.](https://github.com/reptar/reptar/commit/1205d5b8ea59891c51c05c9961b638efae9e9cda)

I'm wondering if you have [your `assets` configuration set up correctly.](https://github.com/reptar/reptar/blob/master/lib/config/config-example.js#L89-L132)

The default config is:

```
assets: [
  { test: /\.s[ac]ss$/, use: 'sass' }
]
```

So if you add that hopefully it should work!

**Comment by dperrera** [comment]
@hswolff Well, that was easy. Thanks! The sass example in the assets configuration threw me. I can whip up some docs on assets if that would help.

One other thing came up while compiling. Reptar is compiling every .sass file into CSS. The convention I've always used is that files that start with an underscore *don't* get compiled into their own css files, they only get imported in to files that ask for them. Is that as simple as a regex or is there a better way to handle that?

**Comment by hswolff** [comment]
That is currently the state of Reptar. Right now Reptar considers every file on an individual basis and passes it through the transforms that it has knowledge about. Which means that even though one `.sass` file imports another `.sass` file, which will work fine, Reptar will still transform both `.sass` files on an individual basis as well.

Opened #77 to continue this discussion.
