### ISSUE TITLE
Empty or non-existent _posts folder results in "Unprocessable Entity"

### ISSUE THREAD

**Issue by dstaley** [reptar/reptar#78]
Steps to reproduce:

1. `mkdir no-posts-folder && cd no-posts-folder && reptar init`
2. `rm -rf _posts`
3. `reptar watch`

Expected result:

Reptar renders `_templates/index.html` with an empty loop.

Actual result:

```
{
  "statusCode":422,
  "error":"Unprocessable Entity",
  "message":"Cannot read property 'assetProcessor' of undefined"
}
```

**Comment by hswolff** [comment]
Oho! NIce find!

**Comment by hswolff** [comment]
Fix I went with was to show a prettier error message. The default scaffold site has the `index.html` file derived from all the files on your page, without any files then that file doesn't exist. So to have an empty loop is actually a lot harder than it might appear.
