### ISSUE TITLE
Date minus one

### ISSUE THREAD

**Issue by dperrera** [reptar/reptar#79]
In a post with front matter like this:

``` yaml
---
date: 2016-03-14
---
```

and an associated template tag like this: `{{file.date | date('DD MMM YYYY')}}`

The template is printing "13 Mar 2016", which is one day earlier than it should be. When I include the time it fixes it, like so:

``` yaml
---
date: 2016-03-14 12:00:00
---
```

I'm not sure if that's how it's intended to work but it'd be nice if Reptar output the right date without the time.

**Comment by hswolff** [comment]
Yeah...I've seen this before as well. It might be using UTC implicitly if no time is given, so when taking a date into a datetime it does -4 hours for EST.

Changing the default from UTC doesn't make sense to me, however maybe adding a setting for setting the timezone would be a good solution to this.

**Comment by hswolff** [comment]
The [YAML spec says if no time is provided it's assumed to be in UTC.](http://yaml.org/type/timestamp.html) So the fix I went with was to parse all dates as UTC, seems to be working.
