### ISSUE TITLE
Home Page 

### ISSUE THREAD

**Issue by acodesmith** [reptar/reptar#87]
Having issues rendering a custom home page. I don't want the homepage to be a list of post. I'm not seeing any documentation for how to set the home page. I've tried creating an `index.md` but it is not updating the default index. 

<img width="1235" alt="screen shot 2018-02-01 at 2 54 36 pm" src="https://user-images.githubusercontent.com/821627/35700137-1ea7b01a-0760-11e8-84f8-4629ea1718d1.png">

**Comment by hswolff** [comment]
You may have to remove the permalink for the index in your collection so that it doesn't write that file. For example this line: https://github.com/reptar/reptar/blob/master/lib/config/config-example.js#L78

**Comment by acodesmith** [comment]
The screenshot shows how I've created an `index.md` in the root of the project. It does not change the default url. For example: `http://127.0.0.1:8080/`

**Comment by acodesmith** [comment]
@hswolff That was it!

**Comment by sergeyzwezdin** [comment]
@hswolff @acodesmith Not sure what you have done, could you explain a bit more detailed? I want a custom index page, not a list. What should I put into the config?
